version: "3.9"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
  server:
    build:
      context: server
    depends_on:
      - postgres
    ports:
      - '7000:7000'
      - '8000:8000'
